spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:registerdb
    driverClassName: org.h2.Driver
    username: user
    password: sermaluc
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    open-in-view: false

user:
  validation:
    regex:
      email: '/^((?!\.)[\w-_.]*[^.])(@\w+)(\.\w+(\.\w+)?[^.\W])$/gim'
      password: '^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=.*[@#$%^&+=]).{8,20}$'
app:
  jwtSecret: '3fc68991cb0ccc2f0cad25d4a4317b2cb58e881d'